/**
 * Comprehensive tooltip definitions.
 * Each entry has THREE parts: what / how / good.
 * Frontend renders as a structured mini-card.
 */

const T = (what, how, good) => ({ what, how, good })

export const TOOLTIPS = {
  // ════════════════════════════════════════════════════════════
  // VOLUME / COUNT METRICS
  // ════════════════════════════════════════════════════════════
  "Total Shipments":      T("Total count of shipment records in the selected scope.",
                            "Row count after applying filters.",
                            "Volume only — not a performance metric. Higher just means a bigger network."),
  "Total Deliveries":     T("Count of completed delivery records.",
                            "Sum of shipments where delivery date is recorded.",
                            "Same as total shipments unless mid-flight shipments are excluded."),
  "Total Volume":         T("Sum of all shipments across the period.",
                            "Row count of shipment records.",
                            "Volume only — track YoY change for growth trends."),
  "Total POs":            T("Number of unique Purchase Orders raised.",
                            "Count of distinct PO numbers.",
                            "Indicates demand intensity. Compare to shipments for orders-per-PO insight."),
  "Unique Products":      T("Number of distinct products shipped (by product ID).",
                            "Count of distinct product_id values.",
                            "FMCG networks typically span 100-500 SKUs. Higher diversity = more complexity."),
  "Unique SKUs":          T("Number of distinct stock-keeping units (each SKU is one sellable variant).",
                            "Count of distinct SKU codes.",
                            "More SKUs = more handling complexity but typically more revenue per category."),
  "Categories":           T("Number of distinct product categories.",
                            "Count of distinct category values.",
                            "FMCG typically operates across 5-15 categories. Heavy mix = complex demand patterns."),
  "Active Lanes":         T("Number of unique origin-destination route pairs.",
                            "Count of distinct (origin_city, destination_city) combinations.",
                            "Higher lane count = more network reach but lower per-lane scale economics."),
  "Active Carriers":      T("Number of unique carrier partners handling shipments.",
                            "Count of distinct carrier_id values.",
                            "5-15 carriers gives leverage. Over 20 = fragmented spend, harder to negotiate."),
  "Origin Cities":        T("Distinct cities your shipments originate from.",
                            "Count of distinct origin_city values.",
                            "Concentrated origins (1-3) = simpler; dispersed origins = more first-mile complexity."),
  "Destination Cities":   T("Distinct cities your shipments deliver to.",
                            "Count of distinct destination_city values.",
                            "Reflects market footprint. Larger = better reach but more last-mile cost."),
  "Unique Origins":       T("Number of distinct origin cities in your network.",
                            "Count of distinct origin_city values.",
                            "Same as Origin Cities. Concentration around 3-5 hubs is typical for FMCG."),
  "States Covered":       T("Number of unique Indian states the network serves.",
                            "Count of distinct destination states.",
                            "India has 28 states + 8 UTs. Coverage of 15+ is a national network."),
  "Tiers Active":         T("Number of supply chain tiers currently in operation.",
                            "Count of distinct tier types: T2, T1, MF, NH, RD, LD, DT, RT.",
                            "Full 8-tier coverage = end-to-end FMCG distribution from supplier to retailer."),
  "Years Covered":        T("Number of distinct calendar years in the dataset.",
                            "Count of distinct ship_date years.",
                            "3+ years gives meaningful YoY analysis. 1 year is just a snapshot."),
  "Active Months":        T("Number of months with at least one shipment.",
                            "Count of distinct year-month combinations.",
                            "36 months = three years of full coverage."),

  // ════════════════════════════════════════════════════════════
  // COST METRICS
  // ════════════════════════════════════════════════════════════
  "Total Cost":              T("Sum of all shipment-level costs (freight + handling + warehousing + packaging + insurance + fuel surcharge).",
                               "Sum of total_cost column across filtered rows.",
                               "Track YoY growth. >12% growth without volume growth = inflation or efficiency loss."),
  "Latest Year Cost":        T("Total shipment cost for the most recent year.",
                               "Sum of total_cost where year = latest available.",
                               "Compare to prior year (YoY Cost KPI) to spot trend direction."),
  "Top Cat. Cost":           T("Total cost of the highest-spend product category.",
                               "Category with maximum total_cost sum.",
                               "If one category dominates (>40% of spend), it's the biggest negotiation lever."),
  "Avg Cost / Kg":           T("Cost per kilogram shipped — best efficiency benchmark across mixed shipments.",
                               "Mean of cost_per_kg across all shipments.",
                               "FMCG India benchmark: ₹8-15/kg for FTL, ₹12-25/kg for LTL. Higher = inefficient."),
  "Avg Cost / Km":           T("Average freight cost per kilometer of distance traveled.",
                               "Mean of cost_per_km across all shipments.",
                               "Useful for lane benchmarking. Indian road freight: ~₹35-50/km/ton typical."),
  "Avg Cost / Unit":         T("Total cost divided by units shipped — best for comparing similar SKUs.",
                               "Mean of cost_per_unit.",
                               "Most useful within a single category. Comparing across categories misleads."),
  "Avg ₹/Kg":                T("Cost per kilogram — best for cross-shipment cost comparison.",
                               "Mean of cost_per_kg.",
                               "Industry typical: ₹8-15/kg FTL, ₹12-25/kg LTL."),
  "Avg ₹/Km":                T("Cost per kilometer — best for lane-level efficiency.",
                               "Mean of cost_per_km.",
                               "India road freight: ~₹35-50/km/ton."),
  "Inefficient Shipments":   T("Shipments flagged as above-benchmark cost for their lane/weight/mode profile.",
                               "Count where cost_inefficiency_flag = 1.",
                               "<15% is healthy. 20%+ = systematic pricing problem needing renegotiation."),
  "Inefficient":             T("Shipments flagged as above-benchmark cost.",
                               "Count where cost_inefficiency_flag = 1.",
                               "<15% healthy; >20% = systematic issue."),
  "Inefficiency Rate":       T("% of shipments flagged as cost-inefficient.",
                               "(Inefficient shipments ÷ Total shipments) × 100.",
                               "<15% acceptable. Above means rates need renegotiation."),
  "Inefficiency %":          T("% of shipments flagged as cost-inefficient (overpaying vs benchmark).",
                               "(Inefficient shipments ÷ Total shipments) × 100.",
                               "<15% acceptable. Above = rate renegotiation needed."),
  "Avg Cost (Inefficient)":  T("Average total cost of shipments flagged as inefficient.",
                               "Mean of total_cost where cost_inefficiency_flag = 1.",
                               "Gap vs efficient avg = potential savings per shipment if optimized."),
  "Inefficient Avg":         T("Average cost of inefficient shipments.",
                               "Mean of total_cost where cost_inefficiency_flag = 1.",
                               "Gap to efficient average = per-shipment savings opportunity."),
  "CTS as % of Order":       T("Cost-to-Serve as % of order value.",
                               "(Total CTS ÷ Order value) × 100.",
                               "FMCG benchmark: <10-15%. >18% squeezes margins severely."),

  // ════════════════════════════════════════════════════════════
  // SERVICE / PERFORMANCE METRICS
  // ════════════════════════════════════════════════════════════
  "On-Time Delivery":        T("% of shipments delivered on or before the expected delivery date.",
                               "(On-time shipments ÷ Total shipments) × 100. otd_flag averaged.",
                               "FMCG benchmark: 90-95%. <85% causes customer service issues."),
  "OTD %":                   T("On-Time Delivery percentage.",
                               "(On-time shipments ÷ Total shipments) × 100.",
                               "FMCG benchmark: 90-95%. Below 85% = customer complaints rise."),
  "Avg OTD %":               T("Average OTD across all carriers (unweighted).",
                               "Mean of carrier-level OTD percentages.",
                               "Compare to volume-weighted OTD — gap reveals if best carriers have low share."),
  "Avg Delay":               T("Average days late vs expected delivery (positive = late).",
                               "Mean of delay_days. Negative = early.",
                               "Target: <0.5 days. 1-2 days indicates systematic late delivery."),
  "Max Delay":               T("Worst single-shipment delay in days.",
                               "Maximum of delay_days.",
                               "Outliers >7 days indicate process breakdowns worth investigating."),
  "Delay Rate":              T("% of shipments delivered after expected delivery date.",
                               "(Shipments with delay > 0 ÷ Total shipments) × 100.",
                               "<10% is healthy. >20% = chronic late-delivery issues."),
  "Delayed Shipments":       T("Count of shipments delivered late.",
                               "Count where delay_days > 0.",
                               "Track in absolute terms when planning capacity adjustments."),
  "Delayed":                 T("Count of shipments delivered late.",
                               "Count where delay_days > 0.",
                               "Absolute count for capacity planning."),
  "Avg Lead Time":           T("Days from PO creation to actual delivery.",
                               "Mean of lead_time_days.",
                               "FMCG benchmark: 3-7 days domestic. >10 days suggests bottlenecks."),
  "Lead Time":               T("Days from PO creation to actual delivery.",
                               "Mean of lead_time_days.",
                               "Target: 3-7 days. Above = inventory/buffer pressure."),
  "Order → Ship":            T("Days from order placement to dispatch (your fulfillment speed).",
                               "Mean of order_to_ship_days.",
                               "Target: <2 days. Reflects internal warehouse efficiency."),
  "Ship → Delivery":         T("Days from dispatch to customer receipt (carrier transit time).",
                               "Mean of ship_to_delivery_days.",
                               "Target: <5 days domestic. Carrier responsibility."),
  "Order Ship":              T("Fulfillment time — days from order to dispatch.",
                               "Mean of order_to_ship_days.",
                               "<2 days target."),
  "Ship Delivery":           T("Transit time — days from dispatch to delivery.",
                               "Mean of ship_to_delivery_days.",
                               "<5 days domestic target."),

  // ════════════════════════════════════════════════════════════
  // UTILIZATION METRICS (the big story)
  // ════════════════════════════════════════════════════════════
  "Vehicle Utilization":     T("Average % of vehicle capacity actually used. Blends FTL & LTL.",
                               "Mean of vehicle_utilization_weight × 100.",
                               "Industry FTL target: 80%+. Mixed average of 55-65% is normal but masks the FTL/LTL split."),
  "Vehicle Util":            T("Average vehicle weight utilization.",
                               "Mean of vehicle_utilization_weight × 100.",
                               "FTL target: 80%+. Sub-65% blended = check FTL/LTL breakdown on Load Type page."),
  "Avg Utilization":         T("Average % of vehicle capacity used.",
                               "Mean of vehicle_utilization_weight × 100.",
                               "FTL target 80%+. Blended average masks the FTL vs LTL story."),
  "Avg Util":                T("Average vehicle utilization across all shipments.",
                               "Mean of vehicle_utilization_weight × 100.",
                               "FTL target: 80%+. See Load Type page for the split."),
  "Util":                    T("Weight utilization — % of truck capacity used per shipment.",
                               "weight_kg ÷ vehicle_capacity_kg × 100.",
                               "FTL target: 80%+. LTL flagged below 60% as consolidation candidate."),
  "Effective Util":          T("Max of weight and volume utilization per shipment.",
                               "max(weight_util, volume_util). A truck of pillows is full by volume even if light.",
                               "Industry-standard fill rate. FTL target 80%+."),
  "FTL Avg Util":            T("Average fill rate on Full Truck Load shipments.",
                               "Mean of effective_util for FTL shipments.",
                               "Target: 80%+. Below 70% = renegotiate truck size or consolidate orders."),
  "FTL Effective Util":      T("FTL fill rate using max(weight, volume).",
                               "Mean of max(weight_util, volume_util) for FTL shipments × 100.",
                               "Target: 80%+. The single best efficiency metric for dedicated trucks."),
  "FTL Fill Rate":           T("Average % of FTL truck capacity used (effective).",
                               "Mean of max(weight_util, volume_util) for FTL × 100.",
                               "Target: 80%+. Below 70% means dedicated trucks running too empty."),
  "LTL Avg Util":            T("Average fill rate on Less Than Truck Load shipments.",
                               "Mean of effective_util for LTL shipments × 100.",
                               "Below 60% = strong consolidation candidate. Run the simulator."),
  "LTL Effective Util":      T("LTL fill rate using max(weight, volume).",
                               "Mean of max(weight_util, volume_util) for LTL × 100.",
                               "Below 60% = consolidation opportunity. Above 75% means LTL is performing well."),
  "LTL Fill Rate":           T("Average % of LTL truck capacity used.",
                               "Mean of max(weight_util, volume_util) for LTL × 100.",
                               "Below 60% flagged. LTL inherently runs lower than FTL — focus on the 60% line."),
  "FTL Shipments":           T("Full Truck Load — your shipment uses an entire dedicated truck.",
                               "Count where load_type = FTL.",
                               "Lower cost/kg if you can fill the truck. Target 80%+ utilization to justify."),
  "LTL Shipments":           T("Less Than Truck Load — shipment shares the truck with other shippers.",
                               "Count where load_type = LTL.",
                               "Higher cost/kg but flexible. Low utilization = consolidation candidate to FTL."),

  // ════════════════════════════════════════════════════════════
  // CONSOLIDATION METRICS
  // ════════════════════════════════════════════════════════════
  "Consolidation Rate":      T("% of shipments consolidated (multiple orders on one vehicle).",
                               "(Consolidated shipments ÷ Total) × 100.",
                               "FMCG benchmark: 30-50%. Higher = better truck utilization economics."),
  "Consol. Rate":            T("% of shipments consolidated.",
                               "(Consolidated shipments ÷ Total) × 100.",
                               "Target: 30-50% in mature networks."),
  "Opportunity Rate":        T("% of LTL shipments that COULD be consolidated but aren't.",
                               "(LTL shipments with consolidation_score > 60 ÷ Total LTL) × 100.",
                               "High % = lots of untapped savings. Run Consolidation Simulator."),
  "Opportunity %":           T("% of LTL shipments with consolidation potential.",
                               "(High-score LTL ÷ Total LTL) × 100.",
                               "Higher = bigger savings pool. Hit the simulator."),
  "Avg Consolidation Score": T("Algorithm score (0-100) measuring consolidation potential per shipment.",
                               "Composite of weight, route overlap, time-window proximity.",
                               ">60 = strong candidate. >80 = should already be consolidated."),
  "Avg Score":               T("Average consolidation score (0-100).",
                               "Mean of consolidation_score across the slice.",
                               ">60 average = active consolidation opportunity."),
  "High-Score":              T("Shipments with consolidation score > 60.",
                               "Count where consolidation_score > 60.",
                               "Top consolidation candidates. Prioritize these for the simulator."),
  "High-Score Shipments":    T("Shipments with consolidation score > 60.",
                               "Count where consolidation_score > 60.",
                               "Top consolidation targets."),

  // ════════════════════════════════════════════════════════════
  // CARRIER METRICS
  // ════════════════════════════════════════════════════════════
  "Top Carrier":             T("Carrier handling the most shipment volume.",
                               "Carrier with maximum shipment count.",
                               "Volume concentration is fine if performance is strong. Watch single-carrier dependency >40%."),
  "Avg Sustain. Score":      T("Average sustainability rating (0-10) across carriers.",
                               "Mean of sustainability_score weighted by carrier shipments.",
                               "Factors fleet emissions, green practices, certifications. >6 = above-average ESG."),
  "Sustain Score":           T("Sustainability rating (0-10).",
                               "Mean of sustainability_score.",
                               ">6 above-average ESG performance."),

  // ════════════════════════════════════════════════════════════
  // PRODUCT METRICS
  // ════════════════════════════════════════════════════════════
  "Top Category":            T("Category with the highest total spend.",
                               "Category with maximum sum of total_cost.",
                               "Biggest negotiation lever. If >40% of spend, single-supplier risk."),
  "Cold Chain":              T("Shipments requiring temperature-controlled handling (dairy, beverages, etc.).",
                               "Count where temperature_controlled_required = 1.",
                               "Higher cost, stricter SLAs. Track separately for cost-per-kg analysis."),
  "Hazardous":               T("Shipments carrying hazardous goods.",
                               "Count where is_hazardous = 1.",
                               "Compliance-critical, specialized handling. Cannot be consolidated with regular freight."),
  "Return Rate":             T("% of shipments returned by customer.",
                               "(Returned shipments ÷ Total shipments) × 100.",
                               "FMCG benchmark: <3%. >5% indicates quality, packaging, or demand-forecast issues."),
  "Damage Rate":             T("% of shipments damaged in transit.",
                               "(Damaged shipments ÷ Total shipments) × 100.",
                               "FMCG benchmark: <1.5%. >3% indicates handling or packaging problems."),
  "Avg Shelf Life":          T("Average shelf life of shipped products in days.",
                               "Mean of shelf_life_days.",
                               "Short shelf life (<60 days) needs faster lead times to prevent waste."),
  "Shelf Life":              T("Average product shelf life in days.",
                               "Mean of shelf_life_days.",
                               "<60 days = velocity-critical. Lead time becomes the bottleneck."),

  // ════════════════════════════════════════════════════════════
  // TRENDS YoY
  // ════════════════════════════════════════════════════════════
  "YoY Cost":                T("Year-over-year change in total cost.",
                               "((Latest year cost − Prior year cost) ÷ Prior year cost) × 100.",
                               "Positive = cost grew. >12% without volume growth = inflation or efficiency loss."),
  "YoY Shipments":           T("Year-over-year change in shipment count.",
                               "((Latest year shipments − Prior year shipments) ÷ Prior year) × 100.",
                               "Reflects business growth. Compare to YoY Cost to assess cost-per-shipment trend."),
  "YoY OTD":                 T("Year-over-year change in OTD% (in percentage points).",
                               "Latest year OTD − Prior year OTD.",
                               ">0 pp = service improved. <-2 pp = service degradation worth investigating."),
  "YoY Util":                T("Year-over-year change in vehicle utilization (in percentage points).",
                               "Latest year util − Prior year util.",
                               ">+2 pp = real efficiency improvement. Negative = utilization slipping."),

  // ════════════════════════════════════════════════════════════
  // SUSTAINABILITY
  // ════════════════════════════════════════════════════════════
  "CO2 Emissions":           T("Total CO₂ released across all shipments.",
                               "Sum of co2_emission_kg.",
                               "Track YoY reduction. Mode shift to rail = 75% lower CO₂/ton-km vs road."),
  "CO₂ Emissions":           T("Total CO₂ released across all shipments.",
                               "Sum of co2_emission_kg.",
                               "Track YoY. Mode shift opportunities in long-haul Road shipments."),
  "CO2 (kg)":                T("Total carbon emissions in kilograms.",
                               "Sum of co2_emission_kg.",
                               "Compare YoY to track decarbonization progress."),
  "CO₂":                     T("Total carbon emissions across all shipments.",
                               "Sum of co2_emission_kg.",
                               "Track YoY. Major lever: Road-to-Rail on long-haul >800km."),

  // ════════════════════════════════════════════════════════════
  // NETWORK
  // ════════════════════════════════════════════════════════════
  "Network Health":          T("Composite indicator combining route diversity, utilization, and OTD.",
                               "Weighted blend of lane count, util%, and OTD% scaled to 0-100.",
                               ">75 healthy. <60 indicates structural issues in network design."),
  "Avg Distance":            T("Average shipment distance.",
                               "Mean of distance_km.",
                               "Short network (<300km avg) = regional. Long (>800km avg) = national."),
  "Volume":                  T("Sum of all shipments across the period.",
                               "Row count after filters.",
                               "Volume only. Compare YoY for growth."),
  "Cost":                    T("Total shipment cost.",
                               "Sum of total_cost.",
                               "Track YoY change to spot trend direction."),

  // ════════════════════════════════════════════════════════════
  // CHARTS — explainers for chart titles
  // ════════════════════════════════════════════════════════════
  "Monthly Cost & Shipment Trend":  T("Total cost (₹) and shipment count per month.",
                                      "Aggregated by ship_date month.",
                                      "Watch for divergence: cost rising faster than shipments = unit cost inflation."),
  "Cost Breakdown":                 T("Distribution of total cost across components.",
                                      "Sum by component category (freight, handling, warehousing, etc.).",
                                      "Freight typically 60-75% of CTS. Other components shouldn't exceed expected ranges."),
  "Month-over-Month Heatmap":       T("Color-coded grid showing metric values by month and year.",
                                      "Selected metric grouped by (year, month).",
                                      "Spot seasonality patterns and YoY drift visually."),
  "Top 5 Carriers by Volume":       T("Your busiest carriers ranked by shipment count.",
                                      "Top 5 carriers by shipment count, with OTD% and total cost.",
                                      "Concentration of >50% in one carrier creates dependency risk."),
  "Cost Components (Ranked)":       T("Cost components ranked from largest to smallest.",
                                      "Each component as % of total cost.",
                                      "Largest components are biggest negotiation levers."),
  "Cost by Product Category":       T("Total cost grouped by product category.",
                                      "Sum of total_cost by category.",
                                      "Top category by spend is your biggest single optimization opportunity."),
  "Cost by Transport Mode":         T("Total cost and per-km cost by transport mode.",
                                      "Cost aggregated by Road / Rail / Air / Multimodal.",
                                      "Rail is ~50% cheaper than Road on long-haul. Mode mix reveals optimization room."),
  "Top Tier Transitions by Cost":   T("Most expensive tier-to-tier flows.",
                                      "Cost sum by (from_tier → to_tier).",
                                      "High-cost transitions are best candidates for route redesign or carrier renegotiation."),
  "Carrier Performance Scorecard":  T("Full scorecard ranking carriers across multiple dimensions.",
                                      "Per-carrier aggregates: shipments, cost, OTD%, util%.",
                                      "Sort by any column to spot best/worst performers on each dimension."),
  "Top 5 Carriers — Multi-Dimensional": T("Multi-axis comparison of top carriers.",
                                          "Radar chart with 5 dimensions: OTD, util, cost, sustainability, reliability.",
                                          "Balanced shape = consistent performer. Lopsided = trade-offs exist."),
  "Mode Mix per Carrier":           T("How each carrier splits across transport modes.",
                                      "Carrier × mode shipment count.",
                                      "Specialists in one mode often perform better than generalists."),
  "FTL vs LTL Mix per Carrier":     T("Each carrier's share of FTL vs LTL business.",
                                      "Carrier × load_type shipment count.",
                                      "FTL-specialists vs LTL-specialists handle different problem profiles."),
  "Vehicle Utilization Distribution":T("Histogram of how full vehicles run.",
                                       "Shipments bucketed by utilization % (10-point buckets).",
                                       "Right-skewed (toward 100%) = good. Bell around 50% = lots of half-full trucks."),
  "FTL vs LTL by Tier Transition":  T("FTL vs LTL volume split by tier-to-tier flow.",
                                      "Stacked bars: FTL vs LTL counts per transition.",
                                      "Long-haul transitions should be FTL-heavy; last-mile typically LTL."),
  "Consolidation Opportunity Funnel":T("How shipments flow from total → opportunity → actually consolidated.",
                                       "Funnel: Total, Could-Be-Consolidated, Consolidated, Missed Opportunities.",
                                       "Wide gap between 'Could' and 'Actually' = unrealized savings."),
  "Consolidation Score Distribution":T("Histogram of consolidation scores (0-100).",
                                       "Shipments bucketed by score in 10-point buckets.",
                                       "Spike at high scores (>60) = lots of unrealized opportunities."),
  "Consolidation by Carrier":       T("How consolidation rates differ across carriers.",
                                      "Per-carrier consolidation rate %.",
                                      "Best practice transfer: low performers can learn from high-rate carriers."),
  "Top Routes by Consolidation Opportunity": T("Routes with most consolidation potential.",
                                               "Routes ranked by (LTL shipments × consolidation_score).",
                                               "Focus on top 10 — they typically account for 50%+ of savings."),
  "PO Aging — Lead Time Distribution":T("Distribution of PO ages (lead times) across buckets.",
                                        "Bucketed: 0-3d, 4-7d, 8-14d, 15-21d, 22-30d, 31-60d, >60.",
                                        "Right-skewed toward higher buckets = bottleneck somewhere."),
  "Lead Time Decomposition by Tier":T("Breaks lead time into Order-to-Ship and Ship-to-Delivery by tier.",
                                      "Average days split per tier transition.",
                                      "Long Order-to-Ship = warehouse issue. Long Ship-to-Delivery = carrier issue."),
  "Payment Status Distribution":    T("How shipments split across payment statuses (Paid, Pending, Overdue, etc.).",
                                      "Count by payment_status.",
                                      "Overdue >5% indicates AR collection problems impacting cash flow."),
  "Delay Root Cause Pareto":        T("Pareto chart of delay causes (bars + cumulative line).",
                                      "Causes ranked by count, with cumulative % overlay.",
                                      "Classic 80/20 — top 3 causes typically explain 80% of delays."),
  "Delay Heatmap — Month × Root Cause":T("Color grid showing when each delay cause peaks.",
                                         "Delays grouped by (month, root_cause).",
                                         "Vertical stripes = seasonal causes; horizontal = chronic causes."),
  "Delay Performance by Carrier":   T("Each carrier's delay rate and avg delay days.",
                                      "Per-carrier delay metrics.",
                                      "Consistent late performers need SLA conversations or carrier swap."),
  "OTD & Delay by Tier Transition": T("OTD% and avg delay broken down by tier transition.",
                                      "Aggregates per (from_tier → to_tier).",
                                      "Specific weak transitions reveal where service breaks down."),
  "Cost Distribution (Percentiles)":T("Cost percentiles (P10 to P99).",
                                      "total_cost values at each percentile.",
                                      "Wide gap P90-P99 = expensive outliers. Investigate top 1%."),
  "Cost-to-Serve as % of Order Value":T("CTS as % of order value by category.",
                                        "Mean of cts_as_pct_of_order per category.",
                                        ">15% squeezes margins. Categories at this level need review."),
  "Utilization Gap by Carrier":     T("Actual vs target utilization, per carrier.",
                                      "Bar comparison: actual_util vs target_util per carrier.",
                                      "Large negative gaps indicate underperforming carriers or unrealistic targets."),
  "Rolling Trend & Anomalies":      T("Rolling-window trend with anomaly markers.",
                                      "Daily values + N-day rolling average + z-score outliers.",
                                      "Red = unusually high; Blue = unusually low. Outliers worth investigating."),
  "Seasonality Pattern":            T("Average monthly pattern across all years.",
                                      "Average shipments and OTD per calendar month.",
                                      "Spot peak months (capacity planning) and quiet months (maintenance windows)."),
  "Year-over-Year Cost Comparison": T("Cost trend lines, one per year, overlaid.",
                                      "Total cost by month, one line per year.",
                                      "Gaps between lines = YoY cost growth. Convergence = stable cost base."),
  "Category Mix (by Cost)":         T("Share of total cost across product categories.",
                                      "Cost sum per category as % of total.",
                                      "Top 3 categories typically 60-70% of cost. Focus optimization there."),
  "Avg Lead Time by Category":      T("Lead time average grouped by category.",
                                      "Mean lead_time_days per category.",
                                      "Slow categories need faster lead times — especially if shelf life is short."),
  "Velocity × Value Matrix":        T("Products classified by velocity (move-rate) × value (margin).",
                                      "2D heatmap: count of products in each velocity/value cell.",
                                      "Fast-mover/high-value = stock heavily. Slow/low = de-list candidate."),
  "Shelf Life Distribution":        T("Histogram of products grouped by shelf life buckets.",
                                      "Bucketed: <30d, 30-90d, 90-180d, 180-365d, 1-2y, >2y.",
                                      "Short shelf life products need fastest lead times to avoid waste."),
  "Returns & Damage by Category":   T("Return rate and damage rate per category.",
                                      "Per-category return% and damage% bars.",
                                      "Fragile or short-shelf categories run highest — focus packaging there."),
  "Top 15 SKUs":                    T("Top 15 SKUs ranked by selected metric.",
                                      "Top 15 sorted by total cost, shipments, return rate, or damage rate.",
                                      "Highest-spend SKUs are your core business. Highest-return SKUs need investigation."),
  "Top Destination States by Volume":T("Top 20 destination states by shipment count.",
                                       "Count of shipments per destination_state.",
                                       "Volume concentration shows where your market actually is."),
  "India Network Flow":             T("Geographical visualization of shipment flow across India.",
                                      "Map: states colored by volume, arcs show top routes, dots are hub cities.",
                                      "Concentration patterns reveal organic hubs. Sparse states show market gaps."),
  "Transport Mode Mix":             T("How shipments split across transport modes.",
                                      "Stacked bar + 4 detail cards: Road, Rail, Air, Multimodal.",
                                      "Road-heavy networks have CO₂ + cost optimization room via Rail."),
  "Top Corridors":                  T("Top 10 origin-destination corridors by volume.",
                                      "Corridors ranked by shipment count with cost and OTD.",
                                      "These are your bread-and-butter flows. Any optimization here moves the needle."),
  "8-Tier Supply Chain Flow":       T("Visualization of the 8-tier FMCG supply chain.",
                                      "Nodes for each tier; arrows show flows with shipments/cost/util/OTD.",
                                      "Click any node or arrow to inspect. Bottlenecks show as low-util long-distance lanes."),
  "Streamwise Differentiator":      T("How each stream (Outbound, Inbound, Last Mile, Reverse) compares.",
                                      "Per-stream KPIs: shipments, cost, OTD, distance, utilization.",
                                      "Each stream has its own profile. Compare against industry norms for each stream type."),
  "Top Tier-to-Tier Lanes":         T("Top 8 most-trafficked tier transitions.",
                                      "Ranked by shipment count with km, ₹/kg, util%, OTD%.",
                                      "These transitions move the most volume — biggest leverage points."),

  // Hero / overview cards
  "Hi Jayant — how can I help?":    T("AI Assistant entry point.",
                                      "Calls live LLM with tool access to your platform data.",
                                      "Best for: 'what are my top consolidation opportunities?' style questions."),

  "Executive Summary":              T("AI-generated actionable insights from your data.",
                                      "Auto-computed: top opportunity, top risk, carrier gap, sustainability win.",
                                      "Re-runs each time data updates. Click any insight to drill into details."),
}

// ──────────────────────────────────────────────────────────────
// Aliases for variant spellings, abbreviations, currency symbols
// ──────────────────────────────────────────────────────────────
const ALIASES = {
  "avg cost / kg":      "Avg Cost / Kg",
  "avg cost / km":      "Avg Cost / Km",
  "cost / kg":          "Avg Cost / Kg",
  "cost / km":          "Avg Cost / Km",
  "cost / unit":        "Avg Cost / Unit",
  "cost per kg":        "Avg Cost / Kg",
  "cost per km":        "Avg Cost / Km",
  "otd":                "OTD %",
  "otd%":               "OTD %",
  "on time delivery":   "On-Time Delivery",
  "on-time":            "On-Time Delivery",
  "util":               "Vehicle Utilization",
  "utilization":        "Vehicle Utilization",
  "effective utilization": "Effective Util",
  "effective util":     "Effective Util",
  "ftl util":           "FTL Avg Util",
  "ltl util":           "LTL Avg Util",
  "fill rate":          "Effective Util",
  "co2":                "CO2 Emissions",
  "co₂":                "CO2 Emissions",
  "co2 emissions":      "CO2 Emissions",
  "consolidation":      "Consolidation Rate",
  "lead time":          "Avg Lead Time",
  "order to ship":      "Order → Ship",
  "ship to delivery":   "Ship → Delivery",
}

const norm = (s) => {
  if (s == null) return ""
  return String(s)
    .toLowerCase()
    .replace(/[₹$€£]/g, "")
    .replace(/[→⟶↦➜▶]/g, "->")
    .replace(/[/]/g, " / ")
    .replace(/[.,;:()]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

/** Returns the structured object {what, how, good} OR null if not found. */
export const getTooltip = (label) => {
  if (!label) return null

  if (TOOLTIPS[label]) return TOOLTIPS[label]
  const k = norm(label)
  if (!k) return null

  if (ALIASES[k]) {
    const target = ALIASES[k]
    if (TOOLTIPS[target]) return TOOLTIPS[target]
  }
  for (const key of Object.keys(TOOLTIPS)) {
    if (norm(key) === k) return TOOLTIPS[key]
  }
  for (const key of Object.keys(TOOLTIPS)) {
    const nk = norm(key)
    if (nk.length < 3) continue
    if (k.includes(nk) || nk.includes(k)) return TOOLTIPS[key]
  }
  return null
}
